declare @codperfesc int = 1
declare @codgruperf int = 0

-- select * from perfil.perfesc_perfiles_escuela where perfesc_codigo = 1
-- select * from perfil.gruperf_grupos_perfilamiento where gruperf_codperfesc = 1 order by gruperf_orden_general
insert into perfil.gruperf_grupos_perfilamiento 
(gruperf_codperfesc, gruperf_nombre, gruperf_orden_general, gruperf_orden, gruperf_puntos_maximos, gruperf_padre, gruperf_icono) values
(@codperfesc, 'DATOS GENERALES', 0, 0, 0, null, 'ri-user-line')

insert into perfil.gruperf_grupos_perfilamiento 
(gruperf_codperfesc, gruperf_nombre, gruperf_orden_general, gruperf_orden, gruperf_puntos_maximos, gruperf_padre, gruperf_icono) values
(@codperfesc, 'FORMACIÓN y  PRODUCCION ACADEMICA/ FORMATIVA', 1, 1, 3.0, null, 'ri-contacts-book-2-line');select @codgruperf = @@IDENTITY

insert into perfil.gruperf_grupos_perfilamiento 
(gruperf_codperfesc, gruperf_nombre, gruperf_orden_general, gruperf_orden, gruperf_puntos_maximos, gruperf_padre, gruperf_icono) values
	(@codperfesc, 'Doctorado en derecho ', 2, 1, 0, @codgruperf, null),
	(@codperfesc, 'Posgrado:', 3, 2, 0, @codgruperf, null),
	(@codperfesc, 'Diplomados ', 4, 3, 0, @codgruperf, null),
	(@codperfesc, 'Seminarios (mínimo de tiempo 20 horas  y que dada la especialidad no requiera una actualizacion en la materia.', 5, 4, 0, @codgruperf, null),
	(@codperfesc, 'Cursos (minimo 30 horas  y que dada la especialidad no requiera una actualizacion de la materia )', 6, 5, 0, @codgruperf, null),
	(@codperfesc, 'Capacitaciones de especialidad (5 años de vigencia )', 7, 6, 0, @codgruperf, null)
	
insert into perfil.gruperf_grupos_perfilamiento 
(gruperf_codperfesc, gruperf_nombre, gruperf_orden_general, gruperf_orden, gruperf_puntos_maximos, gruperf_padre, gruperf_icono) values
(@codperfesc, 'EXPERIENCIA DOCENTE  y PRODUCCION ACADEMICA', 8, 2, 3.0, null, 'ri-pencil-ruler-line'); select @codgruperf = @@IDENTITY

insert into perfil.gruperf_grupos_perfilamiento 
(gruperf_codperfesc, gruperf_nombre, gruperf_orden_general, gruperf_orden, gruperf_puntos_maximos, gruperf_padre, gruperf_icono) values
	(@codperfesc, 'experiencia docente internacional pregrado o maestria', 9, 1, 0, @codgruperf, null),
	(@codperfesc, 'EXPERIENCIA ACADEMICA DIVERSA', 10, 2, 0, @codgruperf, null)
	
insert into perfil.gruperf_grupos_perfilamiento 
(gruperf_codperfesc, gruperf_nombre, gruperf_orden_general, gruperf_orden, gruperf_puntos_maximos, gruperf_padre, gruperf_icono) values
(@codperfesc, 'EXPERIENCIA PROFESIONAL', 11, 3, 4.0, null, 'ri-profile-line'); select @codgruperf = @@IDENTITY
insert into perfil.gruperf_grupos_perfilamiento 
(gruperf_codperfesc, gruperf_nombre, gruperf_orden_general, gruperf_orden, gruperf_puntos_maximos, gruperf_padre, gruperf_icono) values
	(@codperfesc, 'CARGOS DE DESEMPEÑADOS', 12, 1, 0, @codgruperf, null),
	(@codperfesc, 'PARTICIPACIÓN EN ORGANIZACIONES', 13, 2, 0, @codgruperf, null),
	(@codperfesc, 'PROYECCION SOCIAL', 14, 3, 0, @codgruperf, null),
	(@codperfesc, 'ESPECIALISTA EN AREA DEL DERECHO', 15, 4, 0, @codgruperf, null)


-- select * from perfil.opc_opciones where opc_codperfesc = 1
insert into perfil.opc_opciones (opc_opcion, opc_valor, opc_es_no, opc_codperfesc) values
('Escriba: ', 0.0, 0, @codperfesc), ('No', 0.0, 1, @codperfesc), ('Si', 0.0, 0, @codperfesc)

insert into perfil.opc_opciones (opc_opcion, opc_valor, opc_codperfesc) values
('0.2', 0.2, @codperfesc), ('0.25', 0.25, @codperfesc), ('0.3', 0.3, @codperfesc), ('0.35', 0.35, @codperfesc), ('0.4', 0.4, @codperfesc), ('0.45', 0.45, @codperfesc), 
('0.5', 0.5, @codperfesc), ('0.55', 0.55, @codperfesc), ('0.65', 0.65, @codperfesc), ('0.75', 0.75, @codperfesc), ('0.8', 0.8, @codperfesc), ('1', 1, 1), ('1.25', 1.25, @codperfesc), 
('1.4', 1.4, @codperfesc), ('1.5', 1.5, @codperfesc), ('1.6', 1.6, @codperfesc), ('2', 2, @codperfesc), ('2.5', 2.5, @codperfesc)
--, ('0.0', 0.0, 1), ('0.330 Bajo', 0.25, 1), ('331 a 660 Intermedio', 0.50, 1), ('661 a 990 Avanzado', 0.75, 1)

-- select * from perfil.tippreg_tipo_pregunta
-- select * from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = 1 order by preg_orden_general
insert into perfil.preg_preguntas (preg_codtippreg, preg_codgruperf, preg_orden_general, preg_orden, preg_pregunta, preg_tiene_vencimiento) values
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 0), 1, 1, 'Acreditación docente del MINEDCYT (Es de carácter obligatorio para la revision del perfil)', 1), 
(3, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 0), 2, 2, 'Nombre del docente:', 0), 
(3, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 0), 3, 3, 'Grado académico:', 0), 
(3, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 0), 4, 4, 'Universidad en que se graduó:', 0), 
(3, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 0), 5, 5, 'Año de graduación:', 0), 
(3, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 0), 6, 6, 'Fecha de autozación ejercer la abogacia:', 1), 
(3, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 0), 7, 7, 'Fecha de autorización para ejercer el noriado:', 1)

insert into perfil.preg_preguntas (preg_codtippreg, preg_codgruperf, preg_orden_general, preg_orden, preg_pregunta, preg_tiene_vencimiento, preg_multiples_respuestas) values
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 2), 8, 1, 'a) general', 0, 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 2), 9, 2, 'b) en especialidad', 0, 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 2), 10, 3, 'Maestria en especialidad de derecho', 0, 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 2), 11, 4, 'Maestria en educación', 0, 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 2), 12, 5, 'dos maestrias ( siempre y cuando no se cuente con maestria en educacion , si se cuenta la ponderacion seria de 0.50', 0, 1), 

(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 3), 13, 1, 'a) general', 0, 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 3), 14, 2, 'b) competencias virtuales', 0, 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 3), 15, 3, 'c) especialidad de derecho', 0, 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 3), 16, 4, 'd)  dos o mas  postgrados de especialidad', 0, 1)

insert into perfil.preg_preguntas (preg_codtippreg, preg_codgruperf, preg_orden_general, preg_orden, preg_pregunta, preg_tiene_vencimiento, preg_multiples_respuestas, preg_rango_de_fechas, preg_valor_minimo_permitido, preg_valor_maximo_permitido) values
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 4), 17, 1, 'a) general', 1, 1, 1, -5, 5), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 4), 18, 2, 'b) especialidad', 1, 1, 1, -5, 5), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 4), 19, 3, 'c) internacional', 1, 1, 1, -5, 5)

insert into perfil.preg_preguntas (preg_codtippreg, preg_codgruperf, preg_orden_general, preg_orden, preg_pregunta, preg_tiene_vencimiento, preg_multiples_respuestas, preg_rango_de_fechas, preg_valor_minimo_permitido, preg_valor_maximo_permitido) values
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 5), 20, 1, 'a) general', 1, 1, 1, -5, 5), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 5), 21, 2, 'b) especialidad', 1, 1, 1, -5, 5), 

(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 6), 22, 1, 'a) general', 1, 1, 1, -5, 5), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 6), 23, 2, 'b) especialidad', 1, 1, 1, -5, 5), 

(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 7), 24, 1, 'b)extranjero', 1, 1, 1, -5, 5)

insert into perfil.preg_preguntas (preg_codtippreg, preg_codgruperf, preg_orden_general, preg_orden, preg_pregunta, preg_tiene_vencimiento) values
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 8), 25, 1, 'Docente universitario adjunto por mas de 1 año', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 8), 26, 2, 'Experiencia docente universitario menor a 2 años', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 8), 27, 3, 'Experiencia docente universitario de  2 años a 4 años', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 8), 28, 4, 'Experiencia docente universitario de 4 años a 8 años', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 8), 29, 5, 'Experiencia docente universitario > a 8 años', 1), 

(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 9), 30, 1, 'menos de un año ( al menos un curso, modulo o su equivalente completo', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 9), 31, 2, 'menos de tres  años', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 9), 32, 3, 'experiencia docente en preespecialidad/ equivalente o maestria > de 1 año', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 9), 33, 4, 'experiencia docente en preespecialidad / equivalente o maestrias > de 3 años', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 9), 34, 5, 'experiencia docente en preespecialidad / equivalente o maestrias> de 5 años', 1), 

(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 10), 35, 1, 'capacitador juridico publico o privado', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 10), 36, 2, 'conferencista/ disertador/ expositor/ ponente invitado por ente privado  / publico /  educacion  superior internacional', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 10), 37, 3, 'conferencista/ disertador/ expositor/ ponente  invitado por ente privado  / publico /  educacion superior', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 10), 38, 4, 'webinarios / coloquios impartidos nacionales', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 10), 39, 5, 'webinarios / coloquios impartidos internacionales', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 10), 40, 6, 'consultor externo/ interno/ en la materia en sector publico o privado', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 10), 41, 7, 'Coautoria y autoria de libros, revistas, ensayos, articulos de Derecho', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 10), 42, 8, 'autoria /coautoria de revistas indexadas de derecho', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 10), 43, 9, 'participacion en proyectos de ley / investigaciones/ mesas de trabajo en materia de derecho', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 10), 44, 10, 'material educativo creado para entes publicos o privados', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 10), 45, 11, 'material educativo creado para educacion superior', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 10), 46, 12, 'Asesor de tesis, jurado pregrado', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 10), 47, 13, 'Asesor de tesis, jurado maestria o equivalente', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 10), 48, 14, 'Docente investigador', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 10), 49, 15, 'Reconocimiento, mencion hororifica por su labor educativa/ premios o participacion academica', 1), 

(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 11), 50, 1, 'Tarjeta y sellos de Abogado', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 11), 51, 2, 'Sellos de Notario', 1), 

(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 12), 52, 1, 'Decano, Vicedecano o Director de Escuela', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 12), 53, 2, 'Magistrado', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 12), 54, 3, 'juez de primera instancia', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 12), 55, 4, 'Juez de paz', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 12), 56, 5, 'juez suplente', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 12), 57, 6, 'secretario de sala', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 12), 58, 7, 'secretario de camara', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 12), 59, 8, 'Secretario de Juzgado', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 12), 60, 9, 'colaborador de sala/ asistente de magistrado', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 12), 61, 10, 'colaborador de camara', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 12), 62, 11, 'Colaborador de Juzgado', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 12), 63, 12, 'Procurado o Fiscal', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 12), 64, 13, 'Registrador', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 12), 65, 14, 'Jefatura de area juridica especializada ( publica o privada', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 12), 66, 15, 'Asesor de instituciones publicas o privadas', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 12), 67, 16, 'capacitador CNJ, CSJ u ente afin', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 12), 68, 17, 'Agente diplomatico', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 12), 69, 18, 'Ejercicio libre de prosesión por mas de 3 años', 1), 

(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 13), 70, 1, 'Humanitarias', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 13), 71, 2, 'profesionales de derecho internacionales', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 13), 72, 3, 'Profesionales de derecho', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 13), 73, 4, 'Académicas', 1), 

(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 14), 74, 1, 'participacion en proyeccion social utec < de 1 año', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 14), 75, 2, 'participacion en proyeccion social utec < de 2 años', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 14), 76, 3, 'participacion en proyeccion social utec > de 3  años', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 14), 77, 4, 'participacion en proyectos externos de proyeccion social o afin', 1), 

(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 15), 78, 1, 'abogado en area de especialidad del derecho ( registral, corporativo, aduanero, bancario, civil y mercantil, penal, financiero , etc) de mas de 2 años', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 15), 79, 2, 'abogado en area de especialidad del derecho ( registral, corporativo, aduanero, bancario, civil y mercantil, penal, financiero , etc) de mas de 5 años', 1), 
(1, (select gruperf_codigo from perfil.perfesc_perfiles_escuela inner join perfil.gruperf_grupos_perfilamiento on perfesc_codigo = gruperf_codperfesc where gruperf_codperfesc = @codperfesc and gruperf_orden_general = 15), 80, 3, 'abogado en area de especialidad del derecho ( registral, corporativo, aduanero, bancario, civil y mercantil, penal, financiero , etc) de mas de 10 años', 1)


-- select * from perfil.preg_preguntas
-- select * from perfil.pregopc_preguntas_opciones inner join perfil.preg_preguntas on pregopc_codpreg = preg_codigo inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = 8
-- select * from perfil.opc_opciones where opc_codperfesc = 1
--(select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1)
--(select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.2')

--select * from perfil.pregopc_preguntas_opciones 
insert into perfil.pregopc_preguntas_opciones 
(pregopc_codpreg, pregopc_codopc, pregopc_codtipopc, pregopc_opc_orden) 
values
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 1), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_opcion = 'Si'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 1), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 

((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 2), 1, 2, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 3), 1, 2, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 4), 1, 2, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 5), 1, 4, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 6), 1, 3, 1),
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 7), 1, 3, 1)

insert into perfil.pregopc_preguntas_opciones 
(pregopc_codpreg, pregopc_codopc, pregopc_codtipopc, pregopc_opc_orden) values
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 8), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '2.00'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 8), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 9), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '2.50'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 9), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 10), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '1.00'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 10), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 11), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '1.00'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 11), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 12), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '1.00'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 12), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 13), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.50'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 13), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 14), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.55'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 14), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 15), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.75'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 15), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 16), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '1.50'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 16), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 17), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.50'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 17), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 18), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.75'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 18), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 19), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.80'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 19), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 20), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.25'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 20), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 21), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.50'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 21), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 22), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.20'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 22), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 23), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.40'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 23), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 24), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.65'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 24), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 25), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.25'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 25), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 26), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.50'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 26), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 27), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '1.00'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 27), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 28), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '1.50'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 28), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 29), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '2.00'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 29), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 30), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '1.00'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 30), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 31), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '1.50'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 31), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 32), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '1.00'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 32), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 33), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '1.50'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 33), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 34), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '2.50'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 34), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 35), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.25'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 35), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 36), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.45'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 36), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 37), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.40'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 37), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 38), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.20'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 38), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 39), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.25'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 39), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 40), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.25'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 40), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 41), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.50'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 41), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 42), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.65'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 42), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 43), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.50'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 43), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 44), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.25'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 44), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 45), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.35'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 45), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 46), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.50'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 46), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 47), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.65'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 47), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 48), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.50'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 48), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 49), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.50'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 49), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 50), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.50'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 50), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 51), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '1.50'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 51), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 52), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '1.50'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 52), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 53), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '1.50'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 53), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 54), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '1.25'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 54), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 55), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '1.00'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 55), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 56), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.75'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 56), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 57), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '1.00'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 57), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 58), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '1.00'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 58), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 59), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.75'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 59), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 60), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '1.00'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 60), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 61), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '1.00'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 61), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 62), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.50'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 62), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 63), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '1.25'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 63), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 64), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.75'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 64), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 65), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '1.00'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 65), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 66), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.75'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 66), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 67), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '1.25'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 67), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 68), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.50'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 68), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 69), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '1.00'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 69), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 70), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.25'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 70), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 71), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.30'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 71), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 72), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.25'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 72), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 73), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.25'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 73), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 74), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.25'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 74), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 75), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.35'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 75), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 76), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.40'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 76), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 77), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '0.20'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 77), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 78), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '1.25'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 78), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 79), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '1.40'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 79), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 80), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_valor = '1.60'), 1, 1), 
((select preg_codigo from perfil.preg_preguntas inner join perfil.gruperf_grupos_perfilamiento on preg_codgruperf = gruperf_codigo where gruperf_codperfesc = @codperfesc and preg_orden_general = 80), (select opc_codigo from perfil.opc_opciones where opc_codperfesc = 1 and opc_es_no = 1), 1, 2)
go

-- exec perfil.sp_respuestas_perfilamiento @opcion = 1, @codperfesc = 1, @codigo_empleado = 4291, @codencperf = 1